### ISSUE TITLE
Common Issue

### ISSUE THREAD

**Issue by CLAYJFR05** [EnriqueStrange/androidpinbruteforcepico#1]

**Comment by CLAYJFR05** [comment]
> Most phones now have timers when you exceeded your tries. What's your solution to this?

**Comment by EnriqueStrange** [comment]
> > Most phones now have timers when you exceeded your tries. What's your solution to this?

Maths is the solution.....Create a equation to match the timeout sequence of the phone, implement it in python and boom..!!
